sudo: required

language: cpp

services:
    - docker

before_install:
    - docker pull fedora:29

script:
    - docker run  -v /home/travis/build/usbguard-notifier/:/root/build/ fedora:rawhide /bin/sh -c "cd /root/build; ls -la; pwd; cd usbguard-notifier; dnf install --nogpgcheck -y systemd-devel autoconf automake libtool make ansible usbguard usbguard-dev libnotify libnotify-devel && ./autogen.sh && ./configure --prefix /home/$(id -un) && make"
