sudo: required

language: cpp

services:
    - docker

before_install:
    - docker pull fedora:29

script:
    - docker run  -v /home/travis/build/:/root/build/ fedora:rawhide /bin/sh -c "cd /root/build; ls -la; pwd; cd usbguard-notifier; dnf install --nogpgcheck -y protobuf protobuf-devel libqb libqb-devel librsvg2 librsvg2-devel libnotify libnotify-devel usbguard usbguard-devel autoconf automake libtool make ./autogen.sh && ./configure --prefix /home/$(id -un) && make"
